apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      zipkin:
        # name of the zipkin proxy service
        endpoint: "http://zipkin-service:9411/api/v2/spans"
      prometheus:
        endpoint: "0.0.0.0:8889"
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging, zipkin]

        metrics:
          receivers: [otlp]
          processors: []
          exporters: [logging, prometheus]