receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  file:
    path: ./otel.json
    rotation:
        max_megabytes: 10
      
service:
  telemetry:      
    logs:
      level: debug
      output_paths:
        - ./otel.log
        - stdout
      error_output_paths:
        - ./otel.err
        - stderr
        
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file]
    metrics:
      receivers: [otlp]
      exporters: [file]
    logs:
      receivers: [otlp]
      exporters: [file]
 
 